### ISSUE TITLE
[Question] Specify what version of micropython this project runs on

### ISSUE THREAD

**Issue by BertLindeman** [KWSmit/ble-pico-pybricks#2]
Kees,

Great work. 

Have got the pico-w for a few days, so new to the thing.

I could not (yet) get it to work for me.
Tried to see the advertise data from a TechnicHub and a SpikePrime.

It might help to know what version of micropython you successfully used.
At the moment I run with `MicroPython v1.23.0-preview.322.g5114f2c1e on 2024-03-30; Raspberry Pi Pico W with RP2040
`

Bert

**Comment by KWSmit** [comment]
Hi Bert,

I'm running `MicroPython v1.22.2 on 2024-02-22; Raspberry Pi Pico W with RP2040` on the Pico. Does it detect any advertisement data at all?

**Comment by BertLindeman** [comment]
> Hi Bert,
> 
> I'm running `MicroPython v1.22.2 on 2024-02-22; Raspberry Pi Pico W with RP2040` on the Pico. Does it detect any advertisement data at all?

Yes, Kees. I was too eager and wanted to see the simple advertisment data if the hubs were only blinking blue to indicate they want to be paired.
